import "./globals.css";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Sidebar } from "@/components/sidebar";

export const metadata: Metadata = {
  title: "Dashboard Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={cn(
          "min-h-screen bg-slate-950 text-white font-sans antialiased lg:overflow-hidden",
        )}
      >
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
